# Generated by Django 5.1.3 on 2024-12-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Category', models.CharField(max_length=20)),
                ('Supplier', models.CharField(max_length=20)),
                ('Created_at', models.TimeField()),
                ('Updated_at', models.TimeField()),
                ('choices', models.CharField(max_length=20, verbose_name=[('IN_PROGRESS', 'In Progress'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')])),
            ],
        ),
    ]
