# Generated by Django 5.1.3 on 2024-12-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='choices',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20),
        ),
    ]
