# Generated by Django 5.1.3 on 2024-12-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0002_alter_items_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Updated_at',
            field=models.TimeField(null=True),
        ),
    ]
